# CQ2: Các tỉnh đã giải thể, thời gian tồn tại (sắp theo ngày giải thể)
PREFIX vio:  <https://w3id.org/vi-dbpedia/ontology/>
PREFIX vir:  <https://w3id.org/vi-dbpedia/resource/>
PREFIX dbo:  <http://dbpedia.org/ontology/>
PREFIX dbr:  <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?ten ?thanhLap ?giaiThe WHERE {
  ?x a vio:Tinh ;
     rdfs:label ?ten ;
     dbo:dissolutionDate ?giaiThe .
  OPTIONAL { ?x dbo:foundingDate ?thanhLap }
  FILTER(LANG(?ten) = "vi")
}
ORDER BY ?giaiThe
